server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/DEV_TEST_2
    hikari:
      username: root
      password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

mnf:
  feign:
    login:
      name: login
      url: http://localhost:8081