server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/devtest1
    hikari:
      username: root
      password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

mnf:
  feign:
    login:
      name: login
      uri: http://localhost:8081